apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: encoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encoder
  template:
    metadata:
      labels:
        app: encoder
      annotations:
        prometheus.io/scrape: "true"
    spec:
        containers:
        - name: encoder
          image: encoder
          imagePullPolicy: Never
          securityContext:
            privileged: true
          resources:
            requests:
              ephemeral-storage: "10Gi"
            limits:
              ephemeral-storage: "20Gi"
          env:
          - name: MINIO_URL
            value: "192.168.1.74:32218"
          - name: MINIO_ACCESS_KEY
            value: "minio"
          - name: MINIO_SECRET_KEY
            value: "minio123"
          - name: PG_HOST
            value: "postgres-postgresql"
          - name: PG_USER
            value: "postgres"
          - name: PG_PASSWORD
            value: "postgres123"
          - name: REDIS_HOST
            value: "redis:6379"
          - name: REDIS_PASSWORD
            value: ""
          - name: UPDATED_AT
            value: "Sat Jun  2 22:21:48 PDT 2018"
          - name:  MICRO_REGISTRY
            value:  kubernetes
          - name:  MICRO_BROKER
            value:  rabbitmq
          - name: MICRO_SELECTOR
            value: cache
          - name: MICRO_SERVER_ADDRESS
            value: 0.0.0.0:8080
          - name: MICRO_BROKER_ADDRESS
            value: amqp://admin:password@rabbit-rabbitmq:5672
          - name: JAEGER_SERVICE_NAME
            value: video-encoding-svc
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: OPENTRACING_METRICS_EXPORTER_HTTP_PATH
            value: "/metrics"
          ports:
          - name: hosting-port
            containerPort: 8080
          - name: prometheus
            containerPort: 9090
