// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/encode.proto

/*
Package encoder is a generated protocol buffer package.

It is generated from these files:
	proto/encode.proto

It has these top-level messages:
	Request
	Response
*/
package encoder

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	VideoId string `protobuf:"bytes,1,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type Response struct {
	Filenames []string `protobuf:"bytes,1,rep,name=filenames" json:"filenames,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetFilenames() []string {
	if m != nil {
		return m.Filenames
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "encoder.Request")
	proto.RegisterType((*Response)(nil), "encoder.Response")
}

func init() { proto.RegisterFile("proto/encode.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcd, 0x4b, 0xce, 0x4f, 0x49, 0xd5, 0x03, 0x73, 0x84, 0xd8, 0x21, 0xbc, 0x22,
	0x25, 0x15, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x49, 0x2e, 0x8e, 0xb2,
	0xcc, 0x94, 0xd4, 0xfc, 0xf8, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x76, 0x30,
	0xdf, 0x33, 0x45, 0x49, 0x83, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48,
	0x86, 0x8b, 0x33, 0x2d, 0x33, 0x27, 0x35, 0x2f, 0x31, 0x37, 0xb5, 0x58, 0x82, 0x51, 0x81, 0x59,
	0x83, 0x33, 0x08, 0x21, 0x60, 0x64, 0xc9, 0xc5, 0xe6, 0x0a, 0x36, 0x5a, 0x48, 0x1f, 0xce, 0x12,
	0xd0, 0x83, 0xda, 0xa6, 0x07, 0xb5, 0x4a, 0x4a, 0x10, 0x49, 0x04, 0x62, 0xac, 0x12, 0x43, 0x12,
	0x1b, 0xd8, 0x69, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xcd, 0xc2, 0x9d, 0xb0, 0x00,
	0x00, 0x00,
}
